# Colors
background #000000
foreground #ffffff
background_opacity 0.8

# Color settings
color0 #1c1c1c
color1 #ff0000
color2 #00ff00
color3 #ffff00
color4 #0000ff
color5 #ff00ff
color6 #00ffff
color7 #d0d0d0

# Bright colors
color8 #4d4d4d
color9 #ff3333
color10 #33ff33
color11 #ffff33
color12 #3333ff
color13 #ff33ff
color14 #33ffff
color15 #f5f5f5

# Cursor and selection colors
cursor #ff0000
selection_background #ff0000
selection_foreground #000000

# Font and other configurations
font_size 14
font_family JetBrainsMono Nerd Font

bold_font yes
italic_font yes

