foreground              #00FF00
background              #000000
background_opacity      0.92

color0                  #000000
color8                  #002200
color1                  #00FF00
color9                  #005500
color2                  #00CC00
color10                 #004400
color3                  #55FF55
color11                 #003300
color4                  #00AA00
color12                 #003300
color5                  #00FF55
color13                 #004400
color6                  #00DD00
color14                 #003300
color7                  #00FF00
color15                 #006600

cursor                  #00FF00
cursor_text_color       #000000

url_color               #00FF00

selection_foreground    #000000
selection_background    #00FF00

active_tab_foreground   #000000
active_tab_background   #00FF00

inactive_tab_foreground #005500
inactive_tab_background #000000
tab_bar_background      #000000
tab_bar_margin_width    0
tab_bar_margin_height   0 0
tab_bar_style           powerline
tab_powerline_style     angled
tab_separator           " │"
tab_activity_symbol     "●"
active_tab_font_style   bold
inactive_tab_font_style normal

active_border_color     #00FF00
inactive_border_color   #002200

bell_border_color       #55FF55

mark1_foreground        #000000
mark1_background        #00FF00

mark2_foreground        #000000
mark2_background        #005500

mark3_foreground        #000000
mark3_background        #55FF55
