foreground              #E61C24
background              #000000
background_opacity      0.8
background_blur          0

color0                  #0D0E10
color8                  #1A1B1E
color1                  #E61C24
color9                  #2B2D31
color2                  #9E1B1E
color10                 #1A1B1E
color3                  #FF5555
color11                 #1A1B1E
color4                  #9E1B1E
color12                 #1A1B1E
color5                  #FF0055
color13                 #1A1B1E
color6                  #E61C24
color14                 #1A1B1E
color7                  #E61C24
color15                 #2B2D31

cursor                  #E61C24
cursor_text_color       #1A1B1E

url_color               #E61C24

selection_foreground    #1A1B1E
selection_background    #E61C24

active_tab_foreground   #1A1B1E
active_tab_background   #E61C24

inactive_tab_foreground #2B2D31
inactive_tab_background #0D0E10
tab_bar_background      #0D0E10
tab_bar_margin_width    0
tab_bar_margin_height   0 0
tab_bar_style           powerline
tab_powerline_style     angled
tab_separator           " │"
tab_activity_symbol     "●"
active_tab_font_style   bold
inactive_tab_font_style normal

active_border_color     #E61C24
inactive_border_color   #1A1B1E

bell_border_color       #FF5555

mark1_foreground        #1A1B1E
mark1_background        #E61C24

mark2_foreground        #1A1B1E
mark2_background        #2B2D31

mark3_foreground        #1A1B1E
mark3_background        #FF5555
