foreground              #FF0000
background              #000000
background_opacity      0.92

color0                  #000000
color8                  #220000
color1                  #FF0000
color9                  #550000
color2                  #CC0000
color10                 #440000
color3                  #FF5555
color11                 #330000
color4                  #AA0000
color12                 #330000
color5                  #FF0055
color13                 #440000
color6                  #DD0000
color14                 #330000
color7                  #FF0000
color15                 #660000

cursor                  #FF0000
cursor_text_color       #000000

url_color               #FF0000

selection_foreground    #000000
selection_background    #FF0000

active_tab_foreground   #000000
active_tab_background   #FF0000

inactive_tab_foreground #550000
inactive_tab_background #000000
tab_bar_background      #000000
tab_bar_margin_width    0
tab_bar_margin_height   0 0
tab_bar_style           powerline
tab_powerline_style     angled
tab_separator           " │"
tab_activity_symbol     "●"
active_tab_font_style   bold
inactive_tab_font_style normal

active_border_color     #FF0000
inactive_border_color   #220000

bell_border_color       #FF5555

mark1_foreground        #000000
mark1_background        #FF0000

mark2_foreground        #000000
mark2_background        #550000

mark3_foreground        #000000
mark3_background        #FF5555
