#!/usr/bin/env python3
import random
import sys
import time
import shutil
import os

chars = 'アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン0123456789ABCDEF'

try:
    cols, rows = shutil.get_terminal_size()
except:
    cols, rows = 80, 24

columns = [0] * cols

os.system('clear' if os.name == 'posix' else 'cls')

try:
    while True:
        sys.stdout.write('\033[40m')
        for i in range(cols):
            if columns[i] <= 0:
                char = '\033[92m' + random.choice(chars) + '\033[0m'
                sys.stdout.write(char)
                columns[i] = random.randint(1, 10)
            else:
                if random.random() > 0.9:
                    char = '\033[92m' + random.choice(chars) + '\033[0m'
                    sys.stdout.write(char)
                else:
                    char = '\033[32m' + random.choice(chars.lower()) + '\033[0m'
                    sys.stdout.write(char)
                columns[i] -= 1
        sys.stdout.flush()
        time.sleep(0.05)
        sys.stdout.write('\033[H')
except KeyboardInterrupt:
    os.system('clear' if os.name == 'posix' else 'cls')
    sys.exit(0)
