#!/usr/bin/env bash

killall swaync hyprpaper waybar hypridle 2>/dev/null
hyprpaper &
waybar &
swaync &
hypridle &
wl-paste --watch cliphist store &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

udiskie &
swayosd-server &
easyeffects --gapplication-service &