general {
    no_fade_in = false
    grace = 2
    hide_cursor = true
    disable_input = false
}

background {
    path = ~/Pictures/wallpapers/minecraft_1.png
    blur_passes = 3
    blur_size = 5
}

input-field {
    size = 300, 50
    dots_center = true
    outer_color = rgba(255,255,255,0.2)
    inner_color = rgba(255,255,255,0.5)
}
