wallpaper {
	monitor = $first
	path = ~/.config/hypr/walls/matrix-2560x1440.png
	fit_mode = cover
}

# Uncomment if using multi-monitor setup:
# wallpaper {
# monitor = $second
# path = ~/.config/hypr/walls/
# fit_mode = cover
# timeout = $timeout
# }
# wallpaper {
# monitor = $third
# path = ~/.config/hypr/walls/
# fit_mode = cover
# timeout = $timeout
# }

splash = false
