source = ~/.config/hypr/vars.conf

general {
    border_size = $border
    col.inactive_border = rgba($re1$tr5)
    col.active_border = rgba($re0$trF)

    gaps_in = $gapS
    gaps_out = $gapM
}

decoration {
    rounding = $radius
    rounding_power = $power

    active_opacity = $activeTr
    inactive_opacity = $inActiveTr

    blur {
        enabled = true 
        size = $blurSize
        passes = $blurPass
        noise = $noise
        ignore_opacity = true
        new_optimizations = true
        xray = false
        popups = true
    }

    shadow {
        enabled = no
        range = 30
        scale = 2
        render_power = 5
        color = rgba($re0$tr2)
        color_inactive = rgba($no0$tr2)
    }

    dim_inactive = false
    dim_strength = 1
    dim_special = 0
}

group {
    col.border_active = rgba($re0$trF)
    col.border_inactive = rgba($re1$trF)

    col.border_locked_active = rgba($gr0$trF)
    col.border_locked_inactive = rgba($gr1$tr7)

    groupbar {
        col.active = rgba($re0$trF)
        col.inactive = rgba($re1$trF)
        col.locked_active = rgba($gr0$trF)
        col.locked_inactive = rgba($gr1$tr7)
        font_size = $fontM
        text_color = rgba($no0$trF)
        height = 1
        indicator_height = 24
        text_offset = -12
    }
}

animations {
    enabled = false
}
