
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[editor]
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
[language-server.rust-analyzer.config.cargo]
features = "all"


[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }


[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server", # optional
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
